---
title: "Principles of Data Visualization in R Workshop: Introduction"
author: "Willy Chen"
output: html_document
---
Hi!

Welcome to this workshop series on basic data visualization in R. In this series, we will not focus on how to get the R language exactly down. Rather, we will be focusing on learning the minimal things to get the best looking graphs. There is no prerequesites to this workshop and you are not expected to know anything about a computer language. While you are browsing through the workshop, feel free to jump around different sessions to get what you need.

Now, if you have not installed R on your computer, please follow the steps below and then advance to the next work shop session.


# Installing R
R is an object oriented language like Java and Java script and it needs to be installed on your computer for your computer to understand the structure of it. R is open source, meaning it will likely always be free. Unlink Python, there are actually a group of people dedicated to advancing R and hence you can often find updates. Note that sometimes when a new version of R comes out, a lot of things are not supported yet, so I recommend to install **down**. Currently, my version of choice is R 3.6.1 while R 3.2.3  and R 4.0.1 works as well.

To install R, go to the largest *official* repository of R called [CRAN](https://cran.r-project.org) and install the R version of your choice. You can also click the link listed below if you don't want to mess with CRAN.

For MacOS users:

[R 4.0.1](https://cran.r-project.org/bin/macosx/R-4.0.1.pkg)

For Windows users:

[R 4.0.1](https://cran.r-project.org/bin/windows/base/R-4.0.1-win.exe)


Now after you have installed R from CRAN, you would have access to the basic R console. Although the console is good enough to run most things you need, people usually prefer to have a compiler that organizes much better. The most popular R compiler is called [RStudio](https://rstudio.com). RStudio is a company that provides a multitude of free and paid services. 99.9% of the studd you would need are free. To install RStudio on your computer use [this link]() or the links below.

For MacOS users:

[Rstudio for MacOS](https://download1.rstudio.org/desktop/macos/RStudio-1.3.959.dmg)

For Windows users:

[RStudio for Windows](https://download1.rstudio.org/desktop/windows/RStudio-1.3.959.exe)


Everything done by me during this workshop will be done on RStudio. After you have installed RStudio, I recommend you go play around with it. Don't worrt, you will not break your computer from doing so. This is the end of the introduction, I will see you at workshop 1!