---
title: "COVI-19 Resource Lookup"
author: "Resources gathered by volunteers"
date: Updated `r Sys.Date()`
output: html_document
runtime: shiny
---
```{r echo=FALSE,message=FALSE,warning=FALSE,results="hide"}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(shiny)
library(shinythemes)
setwd("~/Documents/GitHub/WillyTheWoo/COVID")
COVID_19_Resource<-read.csv("https://willythewoo.github.io/WillyTheWoo/COVID/COVID-19-Resource.csv")%>%
  separate(State,sep="-",c("State","City"))%>%
  mutate(City=ifelse(is.na(City),"Statewide",City),
         State=str_remove(State," "),
         City=str_remove(City," "))

COVID_19_Resource<-COVID_19_Resource[,!str_detect(variable.names(COVID_19_Resource),regex("X"))]%>%
  arrange(State,City)%>%
  filter(!Date.of.update=="")

names(COVID_19_Resource)<-str_replace_all(variable.names(COVID_19_Resource),pattern="\\.",rep=" ")%>%
  str_replace_all(patter="UI DI",rep="UI/DI")

```

```{r echo=FALSE,message=FALSE,warning=FALSE}
u<-fluidPage(
  # tags$style(".content {background-color: black;
  #            margin-left:-200px}"),
  mainPanel(
    fluidRow(
    column(5,selectInput("state","Select a state",c("All states",unique(str_remove(COVID_19_Resource$State," "))))),
    column(5,(selectInput("city","Select a city",c("Statewide",unique(arrange(COVID_19_Resource,City)$City))))
    #        ),
    # column(5,(selectInput("res","Select a resource",c('All',variable.names(COVID_19_Resource)[!str_detect(variable.names(COVID_19_Resource),regex("Date|Link|notes"))][-c(1,2)])))
           )
    ),

h2("Resources in your selected area"),
h4("Note: UI = Unemployment Insurance, DI = Disability Insurance"),
tabsetPanel(
        tabPanel("Labor",tableOutput("resource")),
        tabPanel("Medical", h2("Coming Soon")),
        tabPanel("Closure & S.I.P.", h2("Coming Soon")),
        tabPanel("Disability & High Risk", h2("Coming Soon")),
        tabPanel("Food", h2("Coming Soon")),
        tabPanel("Rent & Bill Freeze", h2("Coming Soon"))
      )
            ),
  theme = shinytheme("united")
)

s<-function(input, output){
    # observe({
    #      updateSelectInput(session, "city",
    #                        label = "city2",
    #                        choices = filter(COVID_19_Resource,State==input$State)$City,
    #                        selected =filter(COVID_19_Resource,State==input$State)$City[1])
    # })
  
  table <- reactive({
    # if(input$res!="All"){
    #   COVID_19_Resource<-COVID_19_Resource%>%
    #     filter(!is.na(input$res))
    # }
    if(input$state=="All states"){
    COVID_19_Resource
    }else if(input$city=="Statewide"){
    COVID_19_Resource%>%filter(State==input$state)
    }else{
    COVID_19_Resource%>%filter(State==input$state,City==input$city)
    }
    })
  
  
  
  output$resource<-renderTable(table(),hover=TRUE,width="auto")
}

  
shinyApp(ui = u, server = s, options = list(height = 900, width = 1100))

```


```{r eval=FALSE}
rsconnect::setAccountInfo(name='willychen',
			  token='5B5DCAFF63B32C4F04F0320A52198C34',
			  secret='4lfxUC1RDYnrXfydtnQjLfP4AxKGe5EJMW40EIIP')

deployApp(appName="COVID.Rmd", account="willychen")
```

